spring:
  application:
    name: demo_sc
  jpa:
    hibernate:
      ddl-auto: update
    properties:
          hibernate:
            format_sql: true
            show_sql: true
            dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:~/sess_db
    username: sa
    driver-class-name: org.h2.Driver
  h2:
    console:
          enabled: true
          path: /h2-console